Starting evaluation of experiment k-Means-test4-ecg_with_frequency-cfa90897b46b014c796de1ba98df27f8-1
=============================================

Performing execution for UNSUPERVISED algorithm k-Means
Running container 'ghcr.io/timeeval/kmeans:0.3.0' with env='{'LOCAL_UID': '501', 'LOCAL_GID': '501'}' in ExecutionType.EXECUTE mode.
Restricting container to 1.0 CPUs and 15.000 GB RAM

#### Docker container logs ####
useradd warning: user's uid 501 outside of the UID_MIN 1000 and UID_MAX 60000 range.
Traceback (most recent call last):
  File "/app/algorithm.py", line 66, in <module>
    execute(args)
  File "/app/algorithm.py", line 48, in execute
    data = args.ts
  File "/app/algorithm.py", line 23, in ts
    return self.df.iloc[:, 1:-1].values
  File "/app/algorithm.py", line 27, in df
    return pd.read_csv(self.dataInput)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1862, in __init__
    self._open_handles(src, kwds)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1357, in _open_handles
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/test4.cs'

###############################

Docker algorithm failed with status code '1', consider container logs above.
